### ISSUE TITLE
build with ts file orm Typeorm

### ISSUE THREAD

**Issue by Paul75** [camesine/Typescript-restful-starter#13]
In your sample you sur for exemple Sample in config : 

```
entities: [
  Sample
],
```

But me Whencan I use like : 

```
entities: [
  "app/entity/**/*.ts"
],
migrations: [
  "app/migration/**/*.ts"
],
subscribers: [
  "app/subscriber/**/*.ts"
],
```

When I build it have not in js file but ts in the build folder config.

Thanks

**Comment by camesine** [comment]
Updated.. Thanks!

**Comment by Paul75** [comment]
Hello,

No ! I telle a question because now if you compile npm start it failed !

I not have solution yet to user directly ts file to config ....
