### ISSUE TITLE
Routes not works

### ISSUE THREAD

**Issue by Paul75** [camesine/Typescript-restful-starter#15]
I test to launch without modifications and all routes not found, got error 404 ....

Thanks

**Comment by camesine** [comment]
can i see then error?

**Comment by Paul75** [comment]
for exemple : http://localhost:1344/sample indicate : 
{
  "text": "NOT FOUND"
}

**Comment by MattijsE** [comment]
Changing the order of the routes fixed it for me.
Put the route with path "/" last in the array of Router in Router.ts

**Comment by dvxdxm** [comment]
@camesine 
for exemple : http://localhost:1344/product/id  => indicate :
{
"text": "NOT FOUND"
}
How to config router with param id?
