### ISSUE TITLE
Using with pm2 ?

### ISSUE THREAD

**Issue by Paul75** [camesine/Typescript-restful-starter#27]
Hello,

It is simple to execute the project with PM2 Manager ?

Thanks

**Comment by camesine** [comment]
Hi, you can execute with "pm2 start npm -- start" and "pm2 start npm -- run dev"
https://www.npmjs.com/package/pm2

RUN npm install pm2 -g
CMD [ "pm2-runtime", "npm", "--", "start" ]

**Comment by Paul75** [comment]
Hello,

Form me I test do : 

module.exports = {
  apps : [
    {
      name      : 'HEBERGE-EXTRACTION-SERVER-PROD', // name of project in PM2
      script    : './dist/Index.js',
      watch     : './dist',
      env: {
        NODE_ENV: 'development'
      },
      env_production : {
        NODE_ENV: 'production'
      }
    }
  ]
};

in pm2.config.js

And call in package.json : 
"pm2:prod": "npm run build && npm run pm2:start",
    "pm2:start": "pm2 start pm2.config.js --env=production",

It good wrote ?
