### ISSUE TITLE
error in launch

### ISSUE THREAD

**Issue by Paul75** [camesine/Typescript-restful-starter#7]
Hello,

When I do a npm start it say : 
```
Index.ts(24,11): error TS2322: Type 'string | number' is not assignable to type 'number'.
  Type 'string' is not assignable to type 'number'.
config/Database.ts(5,44): error TS2345: Argument of type '{ type: string; host: string; port: number; username: string; password: string; database:string;...' is not assignable to parameter of type 'ConnectionOptions'.
  Type '{ type: string; host: string; port: number; username: string; password: string; database: string;...' is not assignable to type 'SqljsConnectionOptions'.
    Types of property 'type' are incompatible.
      Type 'string' is not assignable to type '"sqljs"'.
```

Thanks

**Comment by camesine** [comment]
Hello,

I can see you local database configuration in [config.ts](https://github.com/camesine/Typescript-restful-starter/blob/master/config.ts) file?.
Maybe is a problem of port configuration on different environments.

Thanks

**Comment by Paul75** [comment]
Yes I see config in the file.

In Visual Studio Code it tell error in Database.ts all lines are red ...

**Comment by Paul75** [comment]
Hello,

The error is when I update all package to the last version.
If I add the package '"@types/node": "^7.0.13",' to '"@types/node": "^9.4.0",' it done the errors ....

**Comment by camesine** [comment]
I checked updates on package.json and solved.
Thanks!!
