### ISSUE TITLE
in dev run error NODE_ENV

### ISSUE THREAD

**Issue by Paul75** [camesine/Typescript-restful-starter#8]
Hello,

Yes it's me again ....

I like your program.

Now In linux or MAC it works but in windows it failed try npm run dev...

I've got : 
```
'NODE_ENV' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
```

Thanks

**Comment by Paul75** [comment]
I don't know if I solved it but I want your great copmment :: 

Use a module "cross-env": "^5.1.3" : 

And in package : 
```
"start": "npm run build && cross-env NODE_ENV=PRODUCTION node dist/Index.js",
"dev": "./node_modules/.bin/nodemon --watch '**/*.ts' --exec cross-env NODE_ENV=DEV ts-node Index.ts",
```

Good or not ?

**Comment by camesine** [comment]
Hello,
If solved error, can send a pull request

**Comment by Paul75** [comment]
nothing to pull ...

**Comment by Paul75** [comment]
When I can create pull request ?

**Comment by camesine** [comment]
When you want to

**Comment by Paul75** [comment]
I add it to change .....
