### ISSUE TITLE
Question : use middlewares

### ISSUE THREAD

**Issue by Paul75** [camesine/Typescript-restful-starter#9]
Hello,

If I understand you use maddlewarein routes ? that means that middlesware for exemple for route Users it works for all (get, post, put,...) ?

And If I want to do for all without one ? exemple I want to restrict access JWT for method post, put, delete but not only for Get ? When I can done ?

Thanks

**Comment by camesine** [comment]
Should remove jwt middleware in config/Router.ts and define it in each route on routes/UsersRoute.ts for example.
